import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docsSidebar: [
    'intro',
    {
      type: 'autogenerated',
      dirName: 'getting-started',
    },
    {
      type: 'autogenerated',
      dirName: 'ios',
    },
    {
      type: 'autogenerated',
      dirName: 'android',
    },
    {
      type: 'autogenerated',
      dirName: 'api',
    },
    {
      type: 'autogenerated',
      dirName: 'guides',
    },
    'contributing',
  ],
  agentsSidebar: [
    'agents/overview',
    'agents/skill',
    'agents/rules',
    'agents/prompts',
  ],
};

export default sidebars;
